### ISSUE TITLE
Possibility to make this work with Control nodes

### ISSUE THREAD

**Issue by db0** [veloc1/3dsprite#1]
This is an awesome work and I'm currently trying to make it work with my [Card Game Framework](https://github.com/db0/godot-card-game-framework). Unfortunately I am basing my card layout on Control nodes and adding this shader to the material of a panel, makes the panel background color disappear. I need to use control nodes so that I modify card information dynamically in the game.

Would it be possible to make this shader work with that? Do you have any ideas how to approach this?

**Comment by db0** [comment]
My initial attempt was using it with a TextureRect instead of a sprite and this is some progress, but the shader tries to treat the texture as a sprite where position 0,0 is the middle of the sprite, whereas in a texturerect, position 0,0 is the top-left corner.

**Comment by veloc1** [comment]
Added UICard.tscn with CanvasItem, check it out. It doesn't have scale though, because I don't have so much experience with UI elements, but I think you can add it entirely in gdscript, just don't forget to update width and height shader params. 

Hope it helps!

**Comment by db0** [comment]
Awesome! Thanks a lot!
